docs_dir: docs/
repo_name: 'CyVerse-learning-materials/data_store_guide'
repo_url: 'https://github.com/CyVerse-learning-materials/data_store_guide'

site_name: 'Changing Your CyVerse Password'
site_description: 'Documentation for CyVerse Platforms and Education'
site_author: 'CyVerse Science Team'
site_url: https://CyVerse-learning-materials.io/data_store_guide

edit_uri: edit/mkdocs/docs

# Copyright
copyright: 'Copyright &copy; 2022 CyVerse'

# Navigation Page
nav:
  - Home: index.md
  - Drag-and-drop Data Transfer with Cyberduck: step1.md
  - Command Line Transfer with iCommands: step2.md
  - Associate Data with Metadata: step3.md
  - Data Sharing and Other Features: step4.md
  - WebDAV: step5.md

# JavaScript for Intercom Widget
extra_javascript:
  - javascripts/intercom-learning.js
  
# Set theme to `readthedocs`
# must also set Action to use `@nomaterial` branch instead of `@master` for material
theme:
  name: readthedocs

  # Default values, taken from mkdocs_theme.yml
  language: en
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Montserrat
    code: Regular
  favicon: assets/favicon.png
  icon:
    logo: material/rocket

# Options
extra:
  social:
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/
    - icon: fontawesome/brands/github
      link: https://github.com/cyverse-learning-material/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cyverseorg
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/cyverse.org
    - icon: fontawesome/brands/docker
      link: https://harbor.cyverse.org/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/CyverseOrgProject
#  analytics:
#    provider: google
#    property: 

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: CyVerse Science Team
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde